### ISSUE TITLE
Implemented blaze apollo

### ISSUE THREAD

**Issue by elie222** [apollostack/blaze-apollo#2]
This looks like what this package should be doing, right?
https://github.com/Swydo/blaze-apollo

**Comment by stubailo** [comment]
Good point! I guess we should close this repository then?

**Comment by elie222** [comment]
It would be good if there was a blaze repo officially supported or at least
recommended by the apollo team.

**Comment by stubailo** [comment]
That's unlikely because we don't use Blaze in production. I think someone who is using the package frequently is the best to maintain it until it gets to a critical mass where a lot of people are relying on it.

**Comment by stubailo** [comment]
Curious what @Swydo thinks - would it be better to have the repository here? Or we should link to it?

**Comment by MiroHibler** [comment]
I'd vote for having it here, but let's hear from @Swydo (@jamiter).

**Comment by stubailo** [comment]
Yeah I think needs to be up to the author. People might have higher expectations about the package if it's on here, and it would be unfair to push that onto someone if they're not into it!

**Comment by jamiter** [comment]
@elie222, thanks for bringing this up and thanks @MiroHibler for the mention!

I agree that if we move it here it will look like an official integration, but it isn't without the Apollo team supporting/developing it. It can be good for some traction but might give people falls hopes. We do plan to keep it up-to-date, because we use it ourselves, but I expect no official support from @stubailo and the Apollo team.

A link in the README of this repo would help people find a working solution though. I know some others like the Q42 guys are also using it in production, but a little more traction would help to get some more feedback and improvements. Or the critical mass that @stubailo mentioned. So +1 for a link in the README!

**Comment by MiroHibler** [comment]
Thank you @jamiter!

I have a small reservation regarding "private" or "unofficial" repos only because I'm afraid that there will be forks which will potentially introduce more confusion to the beginners and newcomers.

Therefore, my suggestion would be a compromise - let's keep it here, so people can easily find it but mention that it's a community effort and not officially supported by Apollo.

I'd also agree with @elie222 that something along the way of "recommended" would be nice, tho ;)

**Comment by stubailo** [comment]
IMO in today's JavaScript world having a lot of decoupled modules maintained by different people is normal. While it causes some confusion if there are multiple solutions for the same problem, that's better than having a single solution that isn't actually guaranteed to be the best.

Let's start with a PR to the readme to link to the other package, and see where to go from there?

**Comment by jamiter** [comment]
There you go!

__P.S.__
_Personally I understand there's a difference in how the Apollo team handles integrations with React, Angular, Angular2 and iOS versus Blaze. It's not only a matter of using it in production (do you really use all of them @stubailo?), but it's simply the size of the user base._

_Blaze is only useable in Meteor and maybe 50% or less actually uses it. The group that uses Meteor + Blaze + Apollo is even smaller. It's not really worth the effort and official support would be a waste of time._

_I understand that that might be hard to swallow for people who invested heavily in Blaze (like us), but I understand. Let them focus on the apollo-client, which we all profit from. We can still build very good packages and integrations ourselves!_
